### ISSUE TITLE
Review by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-infocrew#11]
Hello team Infocrew

Strengths:
The cheat sheet provides a well-curated selection of useful graphs, offering a strong conclusion to the visualization guide.
The project effectively highlights key visualization techniques in a concise format.

Weaknesses:
Additional descriptions are needed to provide context and explain the purpose of the graphs.
Expanding on the explanations would make the poster more informative and accessible to a broader audience.

**Comment by tallapaneniv** [comment]
More description has been added throughout the poster now.

Thank you for your feedback.
