### ISSUE TITLE
Poster Review from Insight Spark

### ISSUE THREAD

**Issue by ronymacwan** [INFO-526-FA24/project-2-infocrew#12]
Strength:
The poster demonstrates a strong focus on educating users, particularly research students, on how to effectively use different visualizations in R based on their data. The inclusion of practical datasets like MPG, Penguin, and Iris flower ensures a diverse range of examples makes the content accessible and relatable to various research fields. 

We are interested in seeing how the different visualizations are selected and tailored to specific datasets. It's crucial to understand how visualizations like bar plots, scatter plots, histograms, and heatmaps can be used effectively for the diverse data types in the chosen datasets.

**Comment by tallapaneniv** [comment]
Thank you.
