### ISSUE TITLE
Instructor Review

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-infocrew#3]
Hello team InfoCrew - 

Overall, your proposal indicates that you are set up for a success. What a great way to review and solidify what you learned over the term AND contribute to future students.  I am excited to see how this comes together.

Note that everyone should be active in GitHub and contributing to the project. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |     0.75   |
| Total    | 10        |   9.75     |

**Comment by tallapaneniv** [comment]
More active participation and contribution from the whole team will be seen.

The poster has been added to the github repo now professor. Thank you for your feedback
