### ISSUE TITLE
MOCK iShowcase - instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-infocrew#4]
Title - match the layout - Tech, Accessibility, comparisons 
Make sure visualization are the same size. 
Include a simple description of the poster project - maybe answer this question: what is the purpose of this poster. 
Visualization sources: 
 
Remove gap between Benefits and Use Cases. 

Accessibility section needs better flow and text. Be specific about the disability (deuteranopia). 
The problem - normal vision vs deutreanopia. 
The solution - color palet and shapes 
And some description too. 

In the comparison section - 
Add text for bar graph and histo 
Correct typo in stacked 

Don't forget the date

**Comment by tallapaneniv** [comment]
Changes to the Title have been made to match the layout.
The visualizations have been re-sized to be of uniform sizes.
Questions included under title which will be answered by the use of Poster.

A Reference section has been added to include the sources of external visualizations.

The spacing between the Benefits and Use Cases has been removed from the "Different Visualization" Section.

The Flow in the Accessibility section has been improved to be presented as a "The Problem" and "The Solution"

The Correction of Typos and inclusion of text in the "Comparison" section have been made.

Also the Date of the iShowcase has been included at the bottom right side of the poster.
