### ISSUE TITLE
Team Peer Review: Data Vizionaries

### ISSUE THREAD

**Issue by hlarya-uoa** [INFO-526-FA24/project-2-infocrew#5]
Strength : good distribution of plots 
Weakness.
Less text with Larger Fonts
Color pallet can be improved
Uniform sizes for plots in boxes

**Comment by tallapaneniv** [comment]
More text has been added with larger Fonts.
The plots have been re-sized to be more uniform.

While the point about the color palette is a bit ambiguous, I am assuming you're talking about the one used in the "Accessibility" section and I will justify the use of that color palette by saying its one of the recommended color palette taught in the class so I opted for that.

Thank you for your feedback.
