### ISSUE TITLE
Peer Review of iShowcase Poster by Team DataWaves

### ISSUE THREAD

**Issue by iam-ajeetsingh** [INFO-526-FA24/project-2-infocrew#7]
Hello Team InfoCrew,

Good Work. Your poster is good but there is scope for improvement in formatting and structure of the poster. 
keep uniformity in visualization sizes, text spacing, etc.

**Comment by tallapaneniv** [comment]
Hello Team Data Waves,

Thank you for your feedback. More consideration has been taken into text spacing and visualization resizing so now its more uniform.
