### ISSUE TITLE
Review from Visual Voyagers

### ISSUE THREAD

**Issue by Tusharvimal** [INFO-526-FA24/project-2-infocrew#8]
1. What is the good thing in the poster?
The topic chosen is pretty interesting and visualization are also good.

2. What do you think can/should be improved?
The approach towards the topic is ambiguous and explore different layout to make the flow of poster more engaging.

**Comment by tallapaneniv** [comment]
improvements have been made to the poster so that there is a possibility of engagement now. Thank you for your feedback.
