### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-infocrew#9]
Strengths: The choice of colors in the visualizations is commendable, as they are thoughtfully designed to be accessible to individuals with color vision deficiencies. This demonstrates a strong commitment to inclusivity and ensures that the project can be understood and appreciated by a broader audience. It reflects an awareness of best practices in data visualization and user experience design.

Weaknesses: While the color scheme is well-considered, the overall plot remains difficult to interpret. The complexity of the visualization or the lack of clarity in presenting key elements might hinder viewers from grasping the intended insights.

**Comment by tallapaneniv** [comment]
Changes have been made to the "Accessibility" section of the poster with the overall flow being presented as the problem and solution so that it can grasped much easier.
